In [2]:
import json
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [3]:
file_path = "/Users/alyssanguyen/Desktop/IRLE_scraping/csv_files/raw_prices_ubereats_ca_ff_03222024.csv"
ca_ff = pd.read_csv(file_path, low_memory = False)
file_path_2 = "/Users/alyssanguyen/Desktop/IRLE_scraping/csv_files/uszips.csv"
ca_zip_count = pd.read_csv(file_path_2)

In [4]:
ca_ff[ca_ff['restaurant_name'] == 'Hardees']

Empty DataFrame
Columns: [Unnamed: 0, restaurant_name, menu_item, menu_item_price, restaurant_location, inputted_location, restaurant_rating, number_of_ratings, restaurant_distance]
Index: []

In [5]:
#Nan values 
nan_count = ca_ff.isnull().sum()
print(nan_count)

Unnamed: 0               0
restaurant_name          0
menu_item                0
menu_item_price          0
restaurant_location    250
inputted_location        0
restaurant_rating        0
number_of_ratings        0
restaurant_distance    235
dtype: int64

In [6]:
#Drop all the columns we don't need 
ca_ff_ = ca_ff.drop(columns=['Unnamed: 0', 'inputted_location','restaurant_distance'])
ca_ff_ = ca_ff_.dropna(subset=['restaurant_location'])

In [7]:
ca_zip_count = ca_zip_count[['zip', 'county_name']]

Exploring missing values

In [8]:
#restaurant_rating cleaning 
# Ensure the column is of string type using .loc
ca_ff_.loc[:, 'restaurant_rating'] = ca_ff_['restaurant_rating'].astype(str)

# Count rows containing 'mi'
rows_with_mi = ca_ff_['restaurant_rating'].str.contains('mi').sum()
print("Number of rows with 'mi' in restaurant rating:", rows_with_mi)

# Replace invalid ratings ending with 'mi' with '0' using .loc
ca_ff_.loc[:, 'restaurant_rating'] = ca_ff_['restaurant_rating'].str.replace(r'.*mi$', '0', regex=True)
ca_ff_ = ca_ff_.dropna()
ca_ff_ = ca_ff_[ca_ff_['menu_item_price'] != 0]

Number of rows with 'mi' in restaurant rating: 3742

In [9]:
#converting data types 
ca_ff_['restaurant_name'] = ca_ff_['restaurant_name'].astype('string')
ca_ff_['menu_item'] = ca_ff_['menu_item'].astype('string')
ca_ff_['menu_item'] = ca_ff_['menu_item'].str.replace(r'\s+', ' ', regex=True)
ca_ff_['restaurant_location'] = ca_ff_['restaurant_location'].astype('string')
ca_ff_['restaurant_rating'] = ca_ff_['restaurant_rating'].str.strip().astype(float)

In [22]:
#cleaning up string columns 

ca_ff_['menu_item'] = ca_ff_['menu_item'].str.lower()
ca_ff_['restaurant_location'] = ca_ff_['restaurant_location'].str.lower()
ca_ff_['restaurant_name'] = ca_ff_['restaurant_name'].str.replace('_', ' ')
ca_ff_['menu_item'] = ca_ff_['menu_item'].str.replace('®', '', regex=False)  # Remove ® symbol
#remove special characters
ca_ff_['menu_item'] = ca_ff_['menu_item'].apply(lambda x: ''.join(ch for ch in x if ch.isalnum() or ch.isspace()))

In [23]:
def price_list(x):
    return list(x)

In [24]:
def mean_non_zero(x):
    return np.mean(x[x != 0]) if np.any(x != 0) else 0

def median_non_zero(x):
    return np.median(x[x != 0]) if np.any(x != 0) else 0

def std_non_zero(x):
    return np.std(x[x != 0]) if np.any(x != 0) else 0

Summary Stats

McDonald's

In [27]:
#Filter to just McDonalds
ca_ff_mcd = ca_ff_[ca_ff_['restaurant_name'] == 'McDonald']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_mcd = ca_ff_mcd.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_mcd.columns = [' '.join(col).strip() for col in grouped_mcd.columns.values]


#Second part of grouping 
mcd_lst = ['big mac', 'big mac meal', 'cheeseburger', 'hamburger', 'medium french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_mcd = ca_ff_mcd[ca_ff_mcd['menu_item'].isin(mcd_lst)].sort_values('menu_item')
menu_items_mcd = menu_items_mcd.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_mcd_2 = menu_items_mcd.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_mcd_2[['specialty_item', 'combo', 'cheeseburger', 'hamburger', 'fries']] = grouped_mcd_2['menu_item_price'].apply(pd.Series)
grouped_mcd_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_mcd = pd.merge(grouped_mcd, grouped_mcd_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_mcd
grouped_mcd

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first
0,McDonald,"100 e redlands blvd, san bernardino, ca, 92408...",6.522047,5.59,4.706970,4.6,127,34
1,McDonald,"1000 e 4th st, long beach, ca, 90802, us",7.439231,5.19,5.679119,4.7,117,137
2,McDonald,"1000 real rd, bakersfield, ca, 93309, us",6.029685,3.69,6.196706,4.9,127,25
3,McDonald,"10051 bruceville road, elk grove, ca, 95757, us",7.812595,5.19,9.957629,4.4,131,19
4,McDonald,"1009 n wilson way, stockton, ca, 95205-4217, us",7.812595,5.19,9.957629,4.5,131,13
...,...,...,...,...,...,...,...,...
223,McDonald,"981 lakeville hwy, petaluma, ca, 94952, us",5.817907,4.29,3.995190,4.7,258,24
224,McDonald,"990 alamo dr, vacaville, ca, 95687, us",8.243897,5.29,9.697837,4.7,136,18
225,McDonald,"chester &amp; brundage, bakersfield, ca, 93304...",5.382640,4.29,3.762974,4.5,125,44
226,McDonald,"mission blvd, santa rosa, ca, 95409, us",5.952109,4.24,4.262860,4.6,128,37
227,McDonald,"nwc roy rogers &amp; la paz plz, victorville, ...",6.090776,4.49,4.239692,4.2,116,50+

Jack in the Box

In [28]:
#Filter to just Jack in the Box
ca_ff_jack = ca_ff_[ca_ff_['restaurant_name'] == 'Jack in the Box']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_jack = ca_ff_jack.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_jack.columns = [' '.join(col).strip() for col in grouped_jack.columns.values]

# #Second part of grouping 
jack_lst = [ 'jumbo jack', 'large french fries', 'large jumbo jack combo']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_jack = ca_ff_jack[ca_ff_jack['menu_item'].isin(jack_lst)].sort_values('menu_item')
menu_items_jack = menu_items_jack.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_jack_2 = menu_items_jack.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()
# grouped_jack_2['menu_item_price'] = grouped_jack_2['menu_item_price'].apply(lambda x: x + [None] * (5 - len(x)) if len(x) < 5 else x[:5])

grouped_jack_2[['specialty_item', 'fries', 'combo']] = grouped_jack_2['menu_item_price'].apply(pd.Series)
grouped_jack_2.drop(columns=['menu_item_price'], inplace=True)

# #Merging the grouped dfs together 
merged_jack = pd.merge(grouped_jack, grouped_jack_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_jack['hamburger'] = np.nan
merged_jack['cheeseburger'] = np.nan

merged_jack

ValueError: Columns must be same length as key

In [61]:
menu_items_jack['menu_item'].unique()

array(['jumbo jack', 'large french fries', 'large jumbo jack combo'],
      dtype=object)

Wendy's

In [62]:
#Filter to just Wendy's
ca_ff_wendy = ca_ff_[ca_ff_['restaurant_name'] == 'Wendy']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'first', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_wendy = ca_ff_wendy.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_wendy.columns = [' '.join(col).strip() for col in grouped_wendy.columns.values]

# #Second part of grouping 
wendy_lst = ['daves combo', 'daves single', 'french fries', 'jr cheeseburger', 'jr hamburger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_wendy = ca_ff_wendy[ca_ff_wendy['menu_item'].isin(wendy_lst)].sort_values('menu_item')
menu_items_wendy = menu_items_wendy.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_wendy_2 = menu_items_wendy.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_wendy_2[['combo', 'specialty_item', 'fries', 'cheeseburger', 'hamburger']] = grouped_wendy_2['menu_item_price'].apply(pd.Series)
grouped_wendy_2.drop(columns=['menu_item_price'], inplace=True)

merged_wendy = pd.merge(grouped_wendy, grouped_wendy_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_wendy

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating first,menu_item count,number_of_ratings first,combo,specialty_item,fries,cheeseburger,hamburger
0,Wendy,"100 scarlet dr., chapel hill, nc, 27517, us",5.922959,3.65,4.401561,4.4,98,480+,10.72,6.45,2.79,2.67,1.94
1,Wendy,"1000 aerial center parkway, morrisville, nc, 2...",5.922959,3.65,4.401561,4.1,98,220+,10.72,6.45,2.79,2.67,1.94
2,Wendy,"10006 w 75th st, merriam, ks, 66204, us",5.993019,4.75,3.471167,4.1,53,300+,7.31,2.92,2.43,NaN,NaN
3,Wendy,"1001 main street, brownsville, tx, 78526, us",5.940202,4.26,4.380769,4.4,99,420+,11.21,7.31,2.67,2.43,1.94
4,Wendy,"101 east ridge road, griffith, in, 46319, us",6.510000,4.26,4.768559,4.1,96,380+,11.33,6.45,2.79,3.28,2.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Wendy,"963 n beach st, ft.worth, tx, 76111, us",5.773273,4.87,3.116635,3.9,110,600+,7.31,2.79,2.18,NaN,NaN
366,Wendy,"9703 kennedy avenue, highland, in, 46322, us",5.809895,3.65,4.231961,4.3,95,140+,10.36,6.45,2.79,2.67,2.31
367,Wendy,"9870 parkway east, birmingham, al, 35215, us",5.658679,4.87,3.071699,3.8,53,420+,7.67,3.16,2.67,NaN,NaN
368,Wendy,"9905 northlake centre pkwy, charlotte, nc, 282...",5.925306,3.65,4.531291,4.1,98,320+,10.97,6.58,2.92,2.43,2.18
369,Wendy,"ocean highway east, leland, nc, 28451, us",5.977500,3.77,4.246008,4.1,96,120+,11.09,6.58,2.92,2.43,2.18

Burger King

In [63]:
#Filter to just Burger King 
ca_ff_bk = ca_ff_[ca_ff_['restaurant_name'] == 'Burger King']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_bk = ca_ff_bk.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_bk.columns = [' '.join(col).strip() for col in grouped_bk.columns.values]

# #Second part of grouping 
#they don't have a plain hamburger FOR NOW using whopper jr 
bk_lst = ['cheeseburger', 'french fries', 'whopper', 'whopper jr', 'whopper meal']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_bk = ca_ff_bk[ca_ff_bk['menu_item'].isin(bk_lst)].sort_values('menu_item')
menu_items_bk = menu_items_bk.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_bk_2 = menu_items_bk.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_bk_2[['cheeseburger', 'fries', 'specialty_item', 'hamburger', 'combo']] = grouped_bk_2['menu_item_price'].apply(pd.Series)
grouped_bk_2.drop(columns=['menu_item_price'], inplace=True)

merged_bk = pd.merge(grouped_bk, grouped_bk_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_bk

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,specialty_item,hamburger,combo
0,Burger King,"100 river oaks cove, georgetown, tx, 78626, us",7.677609,6.190,6.030860,4.0,92,410+,2.69,3.59,7.39,3.59,12.19
1,Burger King,"100 west erie avenue, philadelphia, pa, 19140, us",6.386593,6.250,3.173653,4.1,91,1,2.80,4.40,7.45,4.40,10.10
2,Burger King,"1004 north memorial parkway, huntsville, al, 3...",4.410811,3.465,2.069658,3.8,74,180+,2.79,3.53,7.19,3.89,NaN
3,Burger King,"101 commerce piace west, okatie, sc, 29909, us",7.800100,6.040,5.977699,4.3,100,170+,2.99,3.89,7.79,3.89,13.89
4,Burger King,"102 college park road, ladson, sc, 29456, us",9.827143,8.570,6.280155,4.0,84,230+,2.88,5.20,10.44,5.56,16.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,Burger King,"9440 highway 49 north, gulfport, ms, 39503, us",7.643168,5.990,5.831409,4.2,101,91,3.19,3.59,7.19,4.19,12.79
345,Burger King,"9533 corporation drive, indianapolis, in, 4625...",7.626598,6.350,5.585439,4.3,97,380+,2.49,3.69,7.19,5.19,10.89
346,Burger King,"9650 n. king highway, myrtle beach, sc, 29572, us",9.827143,8.570,6.280155,3.8,84,120+,2.88,5.20,10.44,5.56,16.72
347,Burger King,"974 south academy street, greenville, sc, 2960...",6.182198,6.150,3.121857,4.3,91,310+,2.45,3.90,6.75,3.79,9.55
348,Burger King,"989 thornton road, lithia springs, ga, 30122, us",7.028288,5.300,5.047769,4.2,111,700+,2.87,3.59,6.71,3.95,10.79

Shake Shack

In [64]:
#Filter to just Shake Shack
ca_ff_shake = ca_ff_[ca_ff_['restaurant_name'] == 'Shake Shack']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_shake = ca_ff_shake.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_shake.columns = [' '.join(col).strip() for col in grouped_shake.columns.values]


#Second part of grouping 
shake_lst = ['cheeseburger', 'fries', 'hamburger', 'shackburger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_shake = ca_ff_shake[ca_ff_shake['menu_item'].isin(shake_lst)].sort_values('menu_item')
menu_items_shake = menu_items_shake.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_shake_2 = menu_items_shake.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_shake_2[['cheeseburger', 'fries', 'hamburger', 'specialty_item']] = grouped_shake_2['menu_item_price'].apply(pd.Series)
grouped_shake_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_shake = pd.merge(grouped_shake, grouped_shake_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_shake['combo'] = np.nan

Sonic

In [65]:
#FLAG many missing prices for fries and 
#Filter to just Sonic 
ca_ff_sonic = ca_ff_[ca_ff_['restaurant_name'] == 'Sonic']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_sonic = ca_ff_sonic.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_sonic.columns = [' '.join(col).strip() for col in grouped_sonic.columns.values]


#Second part of grouping 
sonic_lst = ['fries', 'quarter pound double cheeseburger', 'supersonic double cheeseburger', 'supersonic double cheeseburger combo']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_sonic = ca_ff_sonic[ca_ff_sonic['menu_item'].isin(sonic_lst)].sort_values('menu_item')
menu_items_sonic = menu_items_sonic.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_sonic_2 = menu_items_sonic.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_sonic_2['menu_item_price'] = grouped_sonic_2['menu_item_price'].apply(lambda x: x + [None] * (5 - len(x)) if len(x) < 5 else x[:5])

grouped_sonic_2[['fries', 'cheeseburger', 'specialty_item', 'combo', 'hamburger']] = grouped_sonic_2['menu_item_price'].apply(pd.Series)
grouped_sonic_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_sonic = pd.merge(grouped_sonic, grouped_sonic_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_sonic['hamburger'] = np.nan
merged_sonic

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,fries,cheeseburger,specialty_item,combo,hamburger
0,Sonic,"100 n nichols st, fort worth, tx, 76102, us",4.711860,3.95,2.854525,4.3,43,700+,3.83,7.91,NaN,NaN,NaN
1,Sonic,"1000 government street, baton rouge, la, 70802...",5.378500,4.87,3.186047,3.9,40,130+,4.87,9.14,NaN,NaN,NaN
2,Sonic,"1001 tunnel road, asheville, nc, 28805, us",2.935946,2.89,1.189730,4.7,37,32,1.29,2.59,5.29,NaN,NaN
3,Sonic,"1005 south riverfront, dallas, tx, 75207, us",5.664608,4.75,3.588656,4.5,204,2,4.26,7.80,13.51,NaN,NaN
4,Sonic,"10075 w. 75th street, overland park, ks, 66204...",5.271860,4.87,2.849985,4.5,43,290+,4.87,8.28,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,Sonic,"940 ambassador caffery parkway, lafayette, la,...",5.001463,3.89,2.973001,4.5,41,52,4.26,7.92,NaN,NaN,NaN
219,Sonic,"951 montlimar dr, mobile, al, 36609, us",5.659161,4.50,3.685071,4.0,143,500+,4.50,9.38,14.85,NaN,NaN
220,Sonic,"955 manhattan blvd, harvey, la, 70058, us",5.667552,4.50,3.562388,4.4,143,600+,4.38,8.41,14.24,NaN,NaN
221,Sonic,"9801 quivera road, overland park, ks, 66214, us",5.834255,4.71,3.779321,4.2,94,300+,4.59,8.13,13.89,NaN,NaN
222,Sonic,"9829 parkway e, birmingham, al, 35215, us",4.927700,3.65,3.402920,3.8,100,93,4.50,8.04,12.65,NaN,NaN

Five Guys

In [66]:
#Filter for Five Guys
ca_ff_five = ca_ff_[ca_ff_['restaurant_name'] == 'Five Guys']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_five = ca_ff_five.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_five.columns = [' '.join(col).strip() for col in grouped_five.columns.values]


#Second part of grouping 
five_lst = ['cheeseburger', 'little cheeseburger', 'little hamburger', 'regular fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_five = ca_ff_five[ca_ff_five['menu_item'].isin(five_lst)].sort_values('menu_item')
menu_items_five = menu_items_five.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_five_2 = menu_items_five.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_five_2[['specialty_item', 'cheeseburger', 'hamburger', 'fries']] = grouped_five_2['menu_item_price'].apply(pd.Series)
grouped_five_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_five = pd.merge(grouped_five, grouped_five_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_five['combo'] = np.nan
merged_five

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,specialty_item,cheeseburger,hamburger,fries,combo
0,Five Guys,"100 moon shot dr suite 110, madison, al, 35758...",6.838276,6.590,3.056315,4.7,29,280+,11.39,8.87,8.27,5.99,NaN
1,Five Guys,"1000 easton rd., wyncote, pa, 19095, us",8.352759,8.510,3.360459,4.6,58,600+,13.67,10.43,9.35,7.31,NaN
2,Five Guys,"10000 research blvd, austin, tx, 78759, us",8.805714,9.110,3.218897,4.7,28,3,13.67,10.67,9.35,7.67,NaN
3,Five Guys,"1019 fording island rd., suite 101g, bluffton,...",8.344483,8.390,3.323807,4.7,58,800+,13.55,10.55,9.23,7.43,NaN
4,Five Guys,"1028 marble terrace, hoover, al, 35244, us",6.801034,6.590,3.078771,4.9,29,15,11.39,8.87,8.27,5.99,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,Five Guys,"9762 katy fwy, houston, tx, 77055, us",8.456207,8.630,3.245679,4.7,29,2,13.55,10.55,9.23,7.43,NaN
209,Five Guys,"9808 east washington street, indianapolis, in,...",7.406429,7.465,2.611178,4.5,56,1,11.63,9.06,8.22,6.30,NaN
210,Five Guys,"9826 gilead rd., suite c-106, huntersville, nc...",8.182000,8.390,3.198840,4.8,30,1,13.07,10.07,8.87,7.19,NaN
211,Five Guys,"east town center, lincoln hwy. east, lancaster...",8.824483,9.230,3.374954,4.6,29,370+,13.91,11.27,9.71,7.19,NaN
212,Five Guys,"springs at trussville street, center point, al...",8.464483,8.510,3.323807,4.6,29,270+,13.67,10.67,9.35,7.55,NaN

The Habit

In [67]:
ca_ff_habit = ca_ff_[ca_ff_['restaurant_name'] == 'The Habit']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_habit = ca_ff_habit.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_habit.columns = [' '.join(col).strip() for col in grouped_habit.columns.values]


#Second part of grouping 
habit_lst = ['2 original double char meal', 'charburger', 'charburger with cheese', 'double char', 'french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_habit = ca_ff_habit[ca_ff_habit['menu_item'].isin(habit_lst)].sort_values('menu_item')
menu_items_habit = menu_items_habit.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_habit_2 = menu_items_habit.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_habit_2[['combo', 'hamburger', 'cheeseburger', 'specialty_item','fries']] = grouped_habit_2['menu_item_price'].apply(pd.Series)
grouped_habit_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_habit = pd.merge(grouped_habit, grouped_habit_2, on=['restaurant_name', 'restaurant_location'], how='inner')
#merged_five['combo'] = np.nan
merged_habit

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,combo,hamburger,cheeseburger,specialty_item,fries
0,The Habit,"1080 monroe st, albany, ca, 94706, us",12.357179,9.235,11.449412,4.5,78,1,19.12,7.49,8.86,9.99,4.99
1,The Habit,"1122 west wade hampton boulevard, greer, sc, 2...",10.409620,7.860,9.598401,3.9,79,100+,15.87,6.74,7.86,8.74,3.74
2,The Habit,"120 village drive, king of prussia, usa, upper...",10.508312,7.860,9.700927,4.4,77,490+,15.87,6.74,7.86,8.74,3.74
3,The Habit,"1255 s california blvd, walnut creek, ca, 9459...",12.493377,9.360,11.468944,4.4,77,700+,19.12,7.49,8.86,9.99,4.99
4,The Habit,"1412, pinole, ca, 94564, us",12.074810,8.990,11.080844,4.5,79,1,18.73,7.49,8.74,9.86,4.86
5,The Habit,"1489 w. o. ezell boulevard, spartanburg, sc, 2...",10.055000,7.365,10.531790,4.1,62,61,15.87,6.74,7.86,8.74,3.74
6,The Habit,"16291 n marketplace blvd, nampa, id, 83687, us",10.558228,7.860,9.633988,4.3,158,600+,16.24,6.74,7.86,8.74,4.11
7,The Habit,"2050 skibo rd, fayetteville, nc, 28314, us",10.938228,8.740,9.694483,4.0,79,800+,17.24,6.99,8.11,9.24,4.36
8,The Habit,"2206 n eagle rd, meridian, id, 83646, us",10.185694,7.860,8.903632,4.3,72,1,16.24,6.74,7.86,8.74,4.11
9,The Habit,"2245 n university pkwy, provo, ut, 84604, us",9.452639,7.860,6.940256,4.4,72,350+,15.87,6.74,7.86,8.74,3.74
10,The Habit,"260 w union ave, farmington, ut, 84025, us",10.904545,8.740,9.806556,4.2,77,120+,16.86,6.99,8.11,8.86,4.36
11,The Habit,"2640 5th st, alameda, ca, 94501, us",12.293924,9.110,11.390425,4.4,79,1,19.12,7.49,8.86,9.99,4.99
12,The Habit,"3703 battleground avenue, greensboro, nc, 2741...",10.409620,7.860,9.598401,4.2,79,140+,15.87,6.74,7.86,8.74,3.74
13,The Habit,"508 antelope dr, layton, ut, 84041, us",10.395443,7.860,9.603780,4.5,79,500+,15.87,6.74,7.86,8.74,3.74
14,The Habit,"5304 sunset boulevard, lexington, sc, 29072, us",10.055000,7.365,10.531790,4.0,62,61,15.87,6.74,7.86,8.74,3.74
15,The Habit,"6210 calhoun memorial highway, easley, sc, 296...",10.409620,7.860,9.598401,3.9,79,31,15.87,6.74,7.86,8.74,3.74
16,The Habit,"6993 park centre dr, cottonwood heights, ut, 8...",10.931282,8.740,9.746314,4.6,78,800+,16.86,6.99,8.11,8.86,4.36
17,The Habit,"7266 highway 73, catawba springs, nc, 28037, us",10.436964,7.810,11.013407,4.3,56,31,15.87,6.74,7.86,8.74,3.74
18,The Habit,"7677 jordan landing blvd, west jordan, ut, 840...",10.938228,8.740,9.694483,4.5,79,700+,17.24,6.99,8.11,9.24,4.36
19,The Habit,"7740 charlotte highway, indian land, sc, 29707...",10.938228,8.740,9.694483,4.5,79,340+,17.24,6.99,8.11,9.24,4.36

Carl's Jr.

In [68]:
#Filter to Carl's Jr 

ca_ff_carls = ca_ff_[ca_ff_['restaurant_name'] == 'Carls Jr']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_carls = ca_ff_carls.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_carls.columns = [' '.join(col).strip() for col in grouped_carls.columns.values]


#Second part of grouping 
carls_lst = ['california classic double cheeseburger', 'naturalcut french fries', 'single big carl', 'single big carl combo']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_carls = ca_ff_carls[ca_ff_carls['menu_item'].isin(carls_lst)].sort_values('menu_item')
menu_items_carls = menu_items_carls.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_carls_2 = menu_items_carls.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_carls_2[['cheeseburger', 'fries', 'specialty_item','combo']] = grouped_carls_2['menu_item_price'].apply(pd.Series)
grouped_carls_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_carls = pd.merge(grouped_carls, grouped_carls_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_carls['hamburger'] = np.nan
merged_carls

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,specialty_item,combo,hamburger
0,Carls Jr,"1 hallidie plaza, san francisco, ca, 94102, us",10.410000,9.855,4.868432,4.5,54,4,7.23,5.87,12.13,NaN,NaN
1,Carls Jr,"1039 w university ave, georgetown, tx, 78628, us",9.415294,9.150,4.331608,4.6,85,500+,5.15,3.60,7.00,11.80,NaN
2,Carls Jr,"10770 macarthur blvd, oakland, ca, 94605, us",12.728966,13.090,6.153934,4.6,87,600+,6.39,5.19,9.89,16.44,NaN
3,Carls Jr,"1550 fitzgerald drive, pinole, ca, 94564, us",11.091954,10.800,5.363236,4.5,87,500+,6.00,4.55,8.05,13.45,NaN
4,Carls Jr,"1700 w state st, boise, id, 83702, us",9.389080,9.590,4.466085,4.4,87,190+,5.09,3.79,6.39,11.18,NaN
5,Carls Jr,"493 n milwaukee st, boise, id, 83704, us",6.903208,6.390,3.256983,4.4,53,200+,5.09,3.79,6.39,NaN,NaN
6,Carls Jr,"4994 e 41st, tulsa, ok, 74135, us",9.333457,9.490,4.591059,4.2,81,260+,3.11,7.49,11.99,NaN,NaN
7,Carls Jr,"871 marina village pkwy, alameda, ca, 94501, us",8.456447,7.555,4.355249,4.6,76,430+,6.39,5.19,9.89,NaN,NaN
8,Carls Jr,"925 w antelope drive, layton, ut, 84041, us",7.888182,7.690,4.388808,4.5,55,220+,5.09,4.09,7.69,NaN,NaN

In [69]:
#Filter to Hardees's Jr 

ca_ff_hardee = ca_ff_[ca_ff_['restaurant_name'] == 'Hardees']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_hardee = ca_ff_hardee.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_hardee.columns = [' '.join(col).strip() for col in grouped_hardee.columns.values]


#Second part of grouping 
carls_lst = ['big cheeseburger', 'famous star', 'famous star combo', 'naturalcut french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_hardee = ca_ff_hardee[ca_ff_hardee['menu_item'].isin(carls_lst)].sort_values('menu_item')
menu_items_hardee = menu_items_hardee.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_hardee_2 = menu_items_hardee.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_hardee_2[['cheeseburger', 'specialty_item', 'combo','fries']] = grouped_hardee_2['menu_item_price'].apply(pd.Series)
grouped_hardee_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_hardee = pd.merge(grouped_hardee, grouped_hardee_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_hardee['hamburger'] = np.nan
merged_hardee

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,specialty_item,combo,fries,hamburger
0,Hardees,"1 gateway blvd s, savannah, ga, 31419-7551, us",8.390222,6.11,7.328689,4.1,45,100+,5.74,7.99,3.24,NaN,NaN
1,Hardees,"10 e clemmonsville rd, winston salem, nc, 2712...",7.270213,5.67,5.528998,3.9,47,130+,5.19,7.73,2.89,NaN,NaN
2,Hardees,"10 hwy 17 n, surfside beach, sc, 29575, us",7.158750,5.55,5.524208,4.4,48,180+,5.19,7.73,2.89,NaN,NaN
3,Hardees,"100 vandora springs rd., garner, nc, 27529, us",8.322439,8.11,4.509404,3.9,82,370+,5.61,6.86,11.24,NaN,NaN
4,Hardees,"1000 acorn dr, nashville, tn, 37210, us",7.126042,5.55,5.533032,4.4,48,900+,5.19,7.73,2.89,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,Hardees,"9020 east 21st street, indianapolis, in, 46229...",7.263043,5.63,5.857676,4.1,46,170+,5.63,7.67,2.87,NaN,NaN
99,Hardees,"915 army post rd, des moines, ia, 50315, us",7.975294,5.86,7.098046,4.1,51,130+,5.36,7.49,3.24,NaN,NaN
100,Hardees,"917 allison-bonnett memorial dr, hueytown, al,...",7.326596,5.43,5.973593,4.0,47,72,5.19,7.73,2.89,NaN,NaN
101,Hardees,"940 thornton rd., lithia springs, ga, 30122, us",7.415870,6.34,6.170157,4.1,92,500+,6.16,7.13,3.38,NaN,NaN
102,Hardees,"roebuck parkway east &amp; red lane rd, birmin...",7.200638,5.67,5.575119,4.2,47,180+,5.19,7.73,2.89,NaN,NaN

In [70]:
merged_mcd.columns

Index(['restaurant_name', 'restaurant_location',
       'menu_item_price mean_non_zero', 'menu_item_price median_non_zero',
       'menu_item_price std_non_zero', 'restaurant_rating mean',
       'menu_item count', 'number_of_ratings first', 'specialty_item', 'combo',
       'cheeseburger', 'hamburger', 'fries'],
      dtype='object')

In [73]:
#Stack all restaurants
correct_order = [
    'restaurant_name', 'restaurant_location', 'menu_item_price mean_non_zero', 
    'menu_item_price median_non_zero', 'menu_item_price std_non_zero', 
 'menu_item count', 'number_of_ratings first', 'specialty_item', 'combo', 'cheeseburger', 'hamburger', 'fries'
]

dfs = [merged_mcd, merged_jack, merged_wendy, merged_shake, merged_bk, merged_sonic, merged_carls, merged_habit, merged_five, merged_carls, merged_hardee]
dfs = [df[correct_order] for df in dfs]  # Reorder each DataFrame

uber_eats_ff_rnd1_prices = pd.concat(dfs).reset_index(drop=True)

In [76]:
#If there are bad addresses, replace them with the actual address here 

#uber_eats_ff_rnd1_prices.loc[1243, 'restaurant_location'] = "s64w15924 commerce center parkway, muskego, wi, 53150"
uber_eats_ff_rnd1_prices.loc[1546, 'restaurant_location'] = "1052 northside dr. nw, atlanta, ga, 30318"
uber_eats_ff_rnd1_prices.loc[1731, 'restaurant_location'] = "860 peachtree rd ne, atlanta, ga, 30308"

Add location columns

In [77]:
pattern = r",\s*([a-zA-Z]{2})\s*,?\s*(\d{5}(?:-\d{4})?)"

def extract_state_zip(address):
    match = re.search(pattern, address)
    if match:
        state, zip_code = match.groups()
        return state, zip_code
    else:
        return None, None

# Apply the function to extract state and zip code
uber_eats_ff_rnd1_prices[['state', 'zip']] = uber_eats_ff_rnd1_prices['restaurant_location'].apply(lambda x: pd.Series(extract_state_zip(x)))
uber_eats_ff_rnd1_prices['zip'] = uber_eats_ff_rnd1_prices['zip'].str.split('-').str[0].astype(int)

#Get county 
uber_eats_ff_rnd1_prices = uber_eats_ff_rnd1_prices.merge(ca_zip_count, on = 'zip')

In [75]:
nan_zip_rows = uber_eats_ff_rnd1_prices[uber_eats_ff_rnd1_prices['zip'].isna()]
nan_zip_rows

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,menu_item count,number_of_ratings first,specialty_item,combo,cheeseburger,hamburger,fries,state,zip
1546,Five Guys,"1052 northside dr. nw, atlanta, ga, 346, us",8.775116,8.75,3.349374,86,120+,13.91,NaN,10.91,9.59,7.79,None,None
1731,Five Guys,"860 peachtree st ne, atlanta, ga, us, us",8.672353,8.63,3.304724,85,7,13.79,NaN,10.79,9.47,7.67,None,None

Dataset info

In [78]:
specific_date = datetime.strptime('09122024', '%m%d%Y')
# Assign the datetime object to the entire 'date' column
uber_eats_ff_rnd1_prices['date'] = specific_date
uber_eats_ff_rnd1_prices['uber_eats'] = 1
uber_eats_ff_rnd1_prices['post_policy'] = 1
uber_eats_ff_rnd1_prices['fast_food'] = 1
uber_eats_ff_rnd1_prices['local'] = 0

In [47]:
#Save as csv 
uber_eats_ff_rnd1_prices.to_csv('processed_prices_ubereats_nonca_09122024.csv', index = True)