In [2]:
import json
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [37]:
file_path = "/Users/alyssanguyen/Desktop/IRLE_scraping/scripts/raw_prices_ubereats_nonca_fullserv_090142024.csv"
ca_ff = pd.read_csv(file_path)
file_path_2 = "/Users/alyssanguyen/Desktop/IRLE_scraping/csv_files/uszips.csv"
ca_zip_count = pd.read_csv(file_path_2)
# file_path_3 = "/Users/alyssanguyen/Desktop/IRLE_scraping/scripts/raw_prices_ubereats_ca_fullserv_090142024.csv"
# example = pd.read_csv(file_path_3)

# ca_ff = pd.concat([ca_ff, example], axis=0)

# # Reset the index if needed
# ca_ff.reset_index(drop=True, inplace=True)

In [38]:
#Drop all the columns we don't need 
ca_ff_ = ca_ff.drop(columns=['Unnamed: 0', 'inputted_location','restaurant_distance'])
ca_ff_ = ca_ff_.dropna(subset=['restaurant_location'])

In [39]:
ca_zip_count = ca_zip_count[['zip', 'county_name']]

In [40]:
#restaurant_rating cleaning 
# Ensure the column is of string type using .loc
ca_ff_.loc[:, 'restaurant_rating'] = ca_ff_['restaurant_rating'].astype(str)

# Count rows containing 'mi'
rows_with_mi = ca_ff_['restaurant_rating'].str.contains('mi').sum()
print("Number of rows with 'mi' in restaurant rating:", rows_with_mi)

# Replace invalid ratings ending with 'mi' with '0' using .loc
ca_ff_.loc[:, 'restaurant_rating'] = ca_ff_['restaurant_rating'].str.replace(r'.*mi$', '0', regex=True)

Number of rows with 'mi' in restaurant rating: 2047

In [41]:
#converting data types 
ca_ff_['restaurant_name'] = ca_ff_['restaurant_name'].astype('string')
ca_ff_['menu_item'] = ca_ff_['menu_item'].astype('string')
ca_ff_['menu_item'] = ca_ff_['menu_item'].str.replace(r'\s+', ' ', regex=True)
ca_ff_['restaurant_location'] = ca_ff_['restaurant_location'].astype('string')
ca_ff_['restaurant_rating'] = pd.to_numeric(ca_ff_['restaurant_rating'].str.strip(), errors='coerce')

In [42]:
#cleaning up string columns 

ca_ff_['menu_item'] = ca_ff_['menu_item'].str.lower()
ca_ff_['restaurant_location'] = ca_ff_['restaurant_location'].str.lower()
ca_ff_['restaurant_name'] = ca_ff_['restaurant_name'].str.replace('_', ' ')

#remove special characters
ca_ff_['menu_item'] = ca_ff_['menu_item'].apply(lambda x: ''.join(ch for ch in x if ch.isalnum() or ch.isspace()))
ca_ff_

,restaurant_name,menu_item,menu_item_price,restaurant_location,restaurant_rating,number_of_ratings
0,Denny,big tonys wings,9.95,"1709 main street, daphne, al, 36526, us",NaN,NaN
1,Denny,four cheese garlic bread,6.95,"1709 main street, daphne, al, 36526, us",NaN,NaN
2,Denny,classic bruschetta,7.95,"1709 main street, daphne, al, 36526, us",NaN,NaN
3,Denny,fried artichoke hearts,8.95,"1709 main street, daphne, al, 36526, us",NaN,NaN
4,Denny,baked stuffed mushrooms,8.95,"1709 main street, daphne, al, 36526, us",NaN,NaN
...,...,...,...,...,...,...
196202,Denny,milk,3.62,"7541 washington avenue, ocean springs, ms, 395...",4.2,490+
196203,Denny,dasani bottled water,2.69,"7541 washington avenue, ocean springs, ms, 395...",4.2,490+
196204,Denny,hot tea,3.42,"7541 washington avenue, ocean springs, ms, 395...",4.2,490+
196205,Denny,minute maid lemonade,3.62,"7541 washington avenue, ocean springs, ms, 395...",4.2,490+
196206,Denny,sweet cream cold brew,6.02,"7541 washington avenue, ocean springs, ms, 395...",4.2,490+

In [43]:
def price_list(x):
    return list(x)

def mean_non_zero(x):
    return np.mean(x[x != 0]) if np.any(x != 0) else 0

def median_non_zero(x):
    return np.median(x[x != 0]) if np.any(x != 0) else 0

def std_non_zero(x):
    return np.std(x[x != 0]) if np.any(x != 0) else 0

In [44]:
#Outback Steakhouse 

ca_ff_outback = ca_ff_[ca_ff_['restaurant_name'] == 'Outback Steakhouse']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_outback = ca_ff_outback.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_outback.columns = [' '.join(col).strip() for col in grouped_outback.columns.values]

In [45]:
#Second part of grouping 
outback_lst = ['aussie fries','boomerang cheeseburger','the outbacker burger', ]

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_outback = ca_ff_outback[ca_ff_outback['menu_item'].isin(outback_lst)].sort_values('menu_item')
menu_items_outback = menu_items_outback.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_outback_2 = menu_items_outback.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_outback_2[['fries', 'cheeseburger', 'hamburger']] = grouped_outback_2['menu_item_price'].apply(pd.Series)
grouped_outback_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_outback = pd.merge(grouped_outback, grouped_outback_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_outback['combo'] = np.nan
merged_outback['specialty_item'] = np.nan
merged_outback

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,fries,cheeseburger,hamburger,combo,specialty_item
0,Outback Steakhouse,"100 buckwalter parkway, bluffton, sc, 29910, us",18.800980,14.965,13.520533,4.2,214,1,4.99,10.49,13.99,NaN,NaN
1,Outback Steakhouse,"100 n pointe blvd, lancaster, pa, 17601, us",16.552159,13.085,12.144449,4.4,91,800+,4.99,10.49,13.99,NaN,NaN
2,Outback Steakhouse,"10001 westheimer road # 1010, houston, tx, 770...",17.925743,13.990,12.995056,4.5,210,4,4.99,10.49,13.99,NaN,NaN
3,Outback Steakhouse,"10220 north michigan road, carmel, in, 46077, us",17.450515,12.990,13.475626,4.4,198,1,4.99,10.49,13.99,NaN,NaN
4,Outback Steakhouse,"10901 university avenue, clive, ia, 50325, us",18.068762,13.990,13.215370,4.4,108,1,4.99,10.49,13.99,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Outback Steakhouse,"9501 quivira drive, overland park, ks, 66214, us",17.949231,13.990,12.915512,4.5,107,2,4.99,10.49,13.99,NaN,NaN
149,Outback Steakhouse,"9753 fm 1960 bypass, humble, tx, 77338, us",17.947714,13.990,12.853872,4.5,108,2,4.99,10.49,13.99,NaN,NaN
150,Outback Steakhouse,"995 n. peachtree parkway n, peachtree city, ga...",17.787255,13.990,12.831644,4.3,105,2,4.99,10.49,13.99,NaN,NaN
151,Outback Steakhouse,"missingaddress, madison, wi, 53717, us",18.652700,14.965,13.267466,4.4,103,700+,4.99,10.49,13.99,NaN,NaN
152,Outback Steakhouse,"zierdt road &amp; madison boulevard, huntsvill...",18.216667,14.965,13.168075,4.3,99,440+,4.99,10.49,14.99,NaN,NaN

In [46]:
#Red Robin

ca_ff_rr = ca_ff_[ca_ff_['restaurant_name'] == 'Red Robin']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_rr = ca_ff_rr.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_rr.columns = [' '.join(col).strip() for col in grouped_rr.columns.values]

In [47]:
#Second part of grouping 
rr_lst = ['reds cheeseburger','steak fries', ]

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_rr = ca_ff_rr[ca_ff_rr['menu_item'].isin(rr_lst)].sort_values('menu_item')
menu_items_rr = menu_items_rr.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_rr_2 = menu_items_rr.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_rr_2[['cheeseburger', 'fries']] = grouped_rr_2['menu_item_price'].apply(pd.Series)
grouped_rr_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_rr = pd.merge(grouped_rr, grouped_rr_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_rr['combo'] = np.nan
merged_rr['specialty_item'] = np.nan
merged_rr['hamburger'] = np.nan
merged_rr

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,combo,specialty_item,hamburger
0,Red Robin,"10 cabela drive, garner, nc, 27529, us",12.595085,11.69,8.446761,4.5,120,1,8.39,4.79,NaN,NaN,NaN
1,Red Robin,"100, columbia, sc, 29212, us",12.399322,11.09,8.493377,4.4,240,490+,8.39,4.79,NaN,NaN,NaN
2,Red Robin,"1000 greengate centre blvd, greensburg, pa, 15...",12.625246,11.69,8.460137,4.5,124,390+,8.39,4.79,NaN,NaN,NaN
3,Red Robin,"101 east brannon rd, nicholasville, ky, 40356, us",12.178991,10.59,8.686817,4.6,111,410+,8.39,4.79,NaN,NaN,NaN
4,Red Robin,"1020 pittsburgh mills circle, tarentum, pa, 15...",12.465000,11.49,8.441152,4.4,122,360+,8.39,4.79,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Red Robin,"9810 riverside pkwy, tulsa, ok, 74137, us",12.145963,9.59,8.698871,4.3,111,220+,8.39,4.79,NaN,NaN,NaN
83,Red Robin,"9870 von allmen court, louisville, ky, 40241, us",12.563636,10.79,8.820005,4.6,112,470+,8.39,4.79,NaN,NaN,NaN
84,Red Robin,"99 rockingham park blvd #w105, salem, nh, 0307...",12.563636,10.79,8.820005,4.6,112,29,8.39,4.79,NaN,NaN,NaN
85,Red Robin,"9990 e 13th st, wichita, ks, 67206, us",10.655051,11.85,5.447680,4.4,101,1,7.11,3.60,NaN,NaN,NaN
86,Red Robin,"s, 11615 district dr, south jordan, ut, 84095, us",12.751165,12.49,6.714139,4.3,104,210+,9.19,2.49,NaN,NaN,NaN

In [48]:
#Panera

ca_ff_panera = ca_ff_[ca_ff_['restaurant_name'] == 'Panera Bread']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_panera = ca_ff_panera.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_panera.columns = [' '.join(col).strip() for col in grouped_panera.columns.values]

In [49]:
grouped_panera['cheeseburger'] = np.nan
grouped_panera['hamburger'] = np.nan
grouped_panera['specialty_item'] = np.nan
grouped_panera['combo'] = np.nan
grouped_panera['fries'] = np.nan

In [50]:
grouped_panera

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,hamburger,specialty_item,combo,fries
0,Panera Bread,"1 e penn sq, philadelphia, pa, 19107, us",5.695526,4.98,4.830930,4.4,74,400+,NaN,NaN,NaN,NaN,NaN
1,Panera Bread,"10 whitaker street, savannah, ga, 31401, us",16.847000,17.19,7.779779,NaN,110,None,NaN,NaN,NaN,NaN,NaN
2,Panera Bread,"100 e main, league city, tx, 77573, us",5.471875,5.95,1.493054,4.8,160,1,NaN,NaN,NaN,NaN,NaN
3,Panera Bread,"1000 s. 8th street, waco, tx, 76706, us",8.028644,7.49,5.311692,4.6,177,800+,NaN,NaN,NaN,NaN,NaN
4,Panera Bread,"103 west farm to market 544, suite 101, murphy...",8.038231,7.49,5.255773,4.4,526,300+,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Panera Bread,"850 n mayfair rd, wauwatosa, wi, 53226, us",8.217310,7.49,6.481900,NaN,348,None,NaN,NaN,NaN,NaN,NaN
87,Panera Bread,"8803 west 75th street, overland park, ks, 6620...",7.630000,6.59,4.960215,4.7,156,480+,NaN,NaN,NaN,NaN,NaN
88,Panera Bread,"887 south north county boulevard, pleasant gro...",7.801630,7.24,5.121877,NaN,184,None,NaN,NaN,NaN,NaN,NaN
89,Panera Bread,"9309 center lake drive, charlotte, nc, 28216, us",7.852931,7.09,5.436681,4.6,122,1,NaN,NaN,NaN,NaN,NaN
90,Panera Bread,"9905 knockando drive, huntersville, nc, 28078, us",7.493906,6.19,5.285526,4.6,134,900+,NaN,NaN,NaN,NaN,NaN

In [51]:
#Denny

ca_ff_denny = ca_ff_[ca_ff_['restaurant_name'] == 'Denny']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_denny = ca_ff_denny.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_denny.columns = [' '.join(col).strip() for col in grouped_denny.columns.values]

In [52]:
#Second part of grouping 
denny_lst = ['seasoned fries','single cheeseburger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_denny = ca_ff_denny[ca_ff_denny['menu_item'].isin(denny_lst)].sort_values('menu_item')
menu_items_denny = menu_items_denny.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_denny_2 = menu_items_denny.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_denny_2[['fries', 'cheeseburger']] = grouped_denny_2['menu_item_price'].apply(pd.Series)
grouped_denny_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_denny = pd.merge(grouped_denny, grouped_denny_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_denny['combo'] = np.nan
merged_denny['specialty_item'] = np.nan
merged_denny['hamburger'] = np.nan

merged_denny

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,fries,cheeseburger,combo,specialty_item,hamburger
0,Denny,"1-35 north parmer lane, austin, tx, 78753, us",9.220099,8.410,5.503674,4.4,318,700+,4.66,12.78,NaN,NaN,NaN
1,Denny,"101 n. 1200th east, lehi, ut, 84043, us",9.946633,8.250,5.826567,4.3,106,320+,5.39,13.61,NaN,NaN,NaN
2,Denny,"1015 spur 350 west, euless, tx, 76040, us",11.308627,10.955,6.699001,3.9,102,500+,5.81,16.52,NaN,NaN,NaN
3,Denny,"1020 tanger dr., locust grove, ga, 30248, us",11.060500,11.800,6.548664,4.2,100,280+,14.34,NaN,NaN,NaN,NaN
4,Denny,"10433 n. central exprwy, dallas, tx, 75230, us",11.147850,10.070,6.522560,4.4,214,600+,5.81,16.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,Denny,"9567 dyer st, el paso, tx, 79924, us",9.091075,6.690,5.678283,4.5,101,1,4.99,NaN,NaN,NaN,NaN
167,Denny,"9650 s 20th st, oak creek, wi, 53154, us",10.367549,9.030,6.152996,4.3,212,360+,5.81,14.02,NaN,NaN,NaN
168,Denny,"975 s main st, kernersville, nc, 27284, us",9.945417,7.470,6.365291,4.3,202,370+,5.29,13.09,NaN,NaN,NaN
169,Denny,"9766 katy fwy ste b, houston, tx, 77055, us",9.405929,8.690,5.532168,4.4,113,900+,4.59,12.69,NaN,NaN,NaN
170,Denny,"9810 gulf freeway, houston, tx, 77034, us",9.725619,9.340,5.657413,4.1,105,1,5.18,13.19,NaN,NaN,NaN

In [53]:
#Applebee

ca_ff_apple = ca_ff_[ca_ff_['restaurant_name'] == 'Applebee']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_apple = ca_ff_apple.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_apple.columns = [' '.join(col).strip() for col in grouped_apple.columns.values]

In [54]:
#Second part of grouping 
apple_lst = ['classic burger', 'classic cheeseburger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_apple = ca_ff_apple[ca_ff_apple['menu_item'].isin(apple_lst)].sort_values('menu_item')
menu_items_apple = menu_items_apple.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_apple_2 = menu_items_apple.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_apple_2[['hamburger', 'cheeseburger']] = grouped_apple_2['menu_item_price'].apply(pd.Series)
grouped_apple_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_apple = pd.merge(grouped_apple, grouped_apple_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_apple['combo'] = np.nan
merged_apple['specialty_item'] = np.nan
merged_apple['fries'] = np.nan


merged_apple

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,hamburger,cheeseburger,combo,specialty_item,fries
0,Applebee,"101 northern way, york, pa, 17402, us",19.067570,14.19,18.000500,4.1,109,600+,12.49,13.59,NaN,NaN,NaN
1,Applebee,"1020 e state hwy 152, mustang, ok, 73064, us",21.035370,13.59,23.886081,4.2,111,220+,12.39,12.99,NaN,NaN,NaN
2,Applebee,"1041 admiral callaghan lane, vallejo, ca, 9459...",25.874298,17.49,25.873503,4.3,122,900+,15.39,16.69,NaN,NaN,NaN
3,Applebee,"1063 east street road, upper southampton, pa, ...",19.242586,16.49,16.541778,4.5,119,700+,14.99,15.59,NaN,NaN,NaN
4,Applebee,"10655 pendleton pike, indianapolis, in, 46235, us",20.843846,15.99,21.092043,4.2,118,1,13.79,14.99,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Applebee,"9702 airline hwy, baton rouge, la, 70809, us",19.553158,14.49,22.448171,4.1,116,1,13.99,14.39,NaN,NaN,NaN
179,Applebee,"995 i-35, new braunfels, tx, 78130, us",19.368641,15.69,17.987151,4.3,106,800+,13.79,14.99,NaN,NaN,NaN
180,Applebee,"greentree mall, clarksville, in, 47129, us",22.073636,14.19,23.879324,3.9,113,380+,12.39,12.99,NaN,NaN,NaN
181,Applebee,"indian brook dr, dover, nh, 03820, us",25.795738,16.29,26.455125,4.3,122,700+,14.79,15.99,NaN,NaN,NaN
182,Applebee,"w ih 10, san antonio, tx, 78249, us",19.351321,15.99,17.738443,4.4,109,800+,13.79,14.99,NaN,NaN,NaN

In [55]:
#TGI Fridays

ca_ff_tgi = ca_ff_[ca_ff_['restaurant_name'] == 'TGI Fridays']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_tgi = ca_ff_tgi.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_tgi.columns = [' '.join(col).strip() for col in grouped_tgi.columns.values]

In [56]:
#Second part of grouping 
tgi_lst = ['cheeseburger', 'seasoned fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_tgi = ca_ff_tgi[ca_ff_tgi['menu_item'].isin(tgi_lst)].sort_values('menu_item')
menu_items_tgi = menu_items_tgi.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_tgi_2 = menu_items_tgi.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_tgi_2[['cheeseburger', 'fries']] = grouped_tgi_2['menu_item_price'].apply(pd.Series)
grouped_tgi_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_tgi = pd.merge(grouped_tgi, grouped_tgi_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_tgi['combo'] = np.nan
merged_tgi['specialty_item'] = np.nan
merged_tgi['hamburger'] = np.nan
merged_tgi

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,combo,specialty_item,hamburger
0,TGI Fridays,"10 n west end blvd, quakertown, pa, 18951, us",25.521515,18.040,26.537840,4.300000,138,700+,14.82,3.55,NaN,NaN,NaN
1,TGI Fridays,"1100 timber dr e, garner, nc, 27529, us",25.278740,16.320,27.132867,4.400000,266,1,14.02,3.32,NaN,NaN,NaN
2,TGI Fridays,"115 hendersonvile rd, asheville, nc, 28803, us",26.044729,18.390,26.695102,4.100000,135,1,15.94,4.13,NaN,NaN,NaN
3,TGI Fridays,"128 n dupont hwy, new castle, de, 19720, us",25.276929,16.320,27.146043,4.200000,133,1,14.02,3.32,NaN,NaN,NaN
4,TGI Fridays,"1516 s willow st, manchester, nh, 03103, us",24.841145,16.660,26.811302,3.800000,137,1,14.36,3.21,NaN,NaN,NaN
5,TGI Fridays,"15190 crossroads pkwy, gulfport, ms, 39503, us",23.538382,15.170,26.159309,4.100000,142,1,12.87,2.86,NaN,NaN,NaN
6,TGI Fridays,"180 inverness plaza, birmingham, al, 35242, us",12.145372,10.590,11.386965,4.400000,121,1,4.19,NaN,NaN,NaN,NaN
7,TGI Fridays,"1835 n highway 17, mount pleasant, sc, 29464, us",24.249265,15.740,26.492202,4.400000,142,2,13.56,3.21,NaN,NaN,NaN
8,TGI Fridays,"1881 mount zion rd, morrow, ga, 30260, us",25.149690,16.320,26.949638,4.000000,405,4,14.02,3.32,NaN,NaN,NaN
9,TGI Fridays,"2001 holmgren way, green bay, wi, 54304, us",15.795545,18.840,7.863214,4.600000,104,700+,16.89,NaN,NaN,NaN,NaN
10,TGI Fridays,"20430 highway 59 n, humble, tx, 77338, us",11.018205,11.790,11.425837,4.121212,132,94,2.29,NaN,NaN,NaN,NaN
11,TGI Fridays,"20430 highway 59 n, humble, tx, us, us",23.571618,15.400,26.146536,4.400000,284,1,12.98,2.86,NaN,NaN,NaN
12,TGI Fridays,"212 n 4th st, memphis, tn, 38105, us",10.007021,6.990,5.914401,4.500000,51,110+,6.99,NaN,NaN,NaN,NaN
13,TGI Fridays,"221 loudon road, concord, nh, 03301, us",24.841145,16.660,26.811302,4.300000,137,600+,14.36,3.21,NaN,NaN,NaN
14,TGI Fridays,"2502 e springs dr, madison, wi, 53704, us",25.722400,17.240,27.219771,4.400000,131,500+,15.05,3.44,NaN,NaN,NaN
15,TGI Fridays,"2794 parkway, pigeon forge, tn, 37863, us",25.185426,16.430,27.452400,4.200000,270,900+,14.02,3.21,NaN,NaN,NaN
16,TGI Fridays,"2800 oxford dr, bethel park, pa, 15102, us",24.847364,15.740,27.034567,4.200000,405,2,13.56,3.21,NaN,NaN,NaN
17,TGI Fridays,"2871 stonecrest cir, lithonia, ga, 30038, us",23.620428,15.170,25.872800,3.700000,321,700+,14.02,3.32,NaN,NaN,NaN
18,TGI Fridays,"301 rocky run pkwy, wilmington, de, 19803, us",25.271339,16.320,27.146568,4.200000,266,1,14.02,3.32,NaN,NaN,NaN
19,TGI Fridays,"311 north clark road, cedar hill, tx, 75104, us",23.571618,15.400,26.146536,4.200000,568,1,12.98,2.86,NaN,NaN,NaN
20,TGI Fridays,"3301 street rd, bensalem, pa, 19020, us",24.145882,15.800,26.512140,4.300000,426,2,13.33,3.09,NaN,NaN,NaN
21,TGI Fridays,"3502 e 86th st, indianapolis, in, 46240, us",25.982160,18.160,27.182406,4.300000,262,1,15.17,3.21,NaN,NaN,NaN
22,TGI Fridays,"3670 camp creek parkway, atlanta, ga, 30331, us",25.398268,16.320,27.077834,4.200000,266,7,14.02,3.32,NaN,NaN,NaN
23,TGI Fridays,"3700 towne crossing blvd, mesquite, tx, 75150, us",23.571618,15.400,26.146536,4.100000,568,1,12.98,2.86,NaN,NaN,NaN
24,TGI Fridays,"379 main street, salt lake city, ut, 84111, us",5.723187,5.750,3.418930,4.500000,93,140+,6.83,NaN,NaN,NaN,NaN
25,TGI Fridays,"395 s cedar crest blvd, allentown, pa, 18103, us",24.145882,15.800,26.512140,4.300000,142,2,13.33,3.09,NaN,NaN,NaN
26,TGI Fridays,"4000 city ave, philadelphia, pa, 19131, us",24.410813,16.320,25.733114,3.800000,516,7,14.02,3.32,NaN,NaN,NaN
27,TGI Fridays,"409 w wt harris blvd, charlotte, nc, 28262, us",24.847364,15.740,27.034567,4.100000,135,2,13.56,3.21,NaN,NaN,NaN
28,TGI Fridays,"4239 nw expressway st, oklahoma city, ok, 7311...",24.588760,16.430,26.783531,4.500000,270,1,14.02,3.21,NaN,NaN,NaN
29,TGI Fridays,"4402 southmont way, bethlehem, pa, 18045, us",25.521515,18.040,26.537840,4.300000,138,1,14.82,3.55,NaN,NaN,NaN
30,TGI Fridays,"4423 w wendover ave, greensboro, nc, 27407, us",25.100465,16.320,26.970615,4.100000,270,1,14.02,3.32,NaN,NaN,NaN
31,TGI Fridays,"449 opry mills dr, nashville, tn, 37214, us",24.624844,15.570,27.193712,3.900000,268,1,12.87,2.86,NaN,NaN,NaN
32,TGI Fridays,"500 highway 17 north, north myrtle beach, sc, ...",24.249265,15.740,26.492202,4.400000,142,800+,13.56,3.21,NaN,NaN,NaN
33,TGI Fridays,"6220 state route 30, greensburg, pa, 15601, us",24.863346,15.740,27.010849,4.374861,541,390+,13.56,3.21,NaN,NaN,NaN
34,TGI Fridays,"6840 northlake mall dr, charlotte, nc, 28269, us",10.220952,12.790,6.609936,3.700000,47,72,2.79,NaN,NaN,NaN,NaN
35,TGI Fridays,"6840 northlake mall drive, charlotte, nc, 2821...",24.847364,15.740,27.034567,4.100000,405,2,13.56,3.21,NaN,NaN,NaN
36,TGI Fridays,"685 middletown blvd, langhorne, pa, 19047, us",24.145882,15.800,26.512140,4.300000,426,1,13.33,3.09,NaN,NaN,NaN
37,TGI Fridays,"6915 w 38th st, indianapolis, in, 46214, us",26.004960,18.160,27.166250,4.000000,262,900+,15.17,3.78,NaN,NaN,NaN
38,TGI Fridays,"7474 s olympia ave, tulsa, ok, 74132, us",13.967551,12.090,12.013984,4.600000,98,360+,4.19,NaN,NaN,NaN,NaN
39,TGI Fridays,"7515 n kings hwy, myrtle beach, sc, 29572, us",21.328869,12.935,24.717981,4.261364,176,12,13.56,3.21,NaN,NaN,NaN
40,TGI Fridays,"7728 fm 1960 rd w, houston, tx, 77070, us",20.379266,13.590,23.845857,4.300000,188,2,12.98,2.86,NaN,NaN,NaN

In [57]:
#'Buffalo Wild Wings'
#TGI Fridays

ca_ff_buff = ca_ff_[ca_ff_['restaurant_name'] == 'Buffalo Wild Wings']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_buff = ca_ff_buff.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_buff.columns = [' '.join(col).strip() for col in grouped_buff.columns.values]

In [58]:
#Second part of grouping 
buff_lst = ['allamerican cheeseburger', 'regular french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_buff = ca_ff_buff[ca_ff_buff['menu_item'].isin(buff_lst)].sort_values('menu_item')
menu_items_buff = menu_items_buff.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_buff_2 = menu_items_buff.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_buff_2[['cheeseburger', 'fries']] = grouped_buff_2['menu_item_price'].apply(pd.Series)
grouped_buff_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_buff = pd.merge(grouped_buff, grouped_buff_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_buff['combo'] = np.nan
merged_buff['specialty_item'] = np.nan
merged_buff['hamburger'] = np.nan
merged_buff

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,combo,specialty_item,hamburger
0,Buffalo Wild Wings,"100 adams ln, mount juliet, tn, 37122, us",7.691735,6.74,8.860379,4.2,108,1,13.79,4.79,NaN,NaN,NaN
1,Buffalo Wild Wings,"1000 bower pkwy, columbia, sc, 29212, us",7.390729,5.04,8.913631,4.2,212,1,13.79,4.79,NaN,NaN,NaN
2,Buffalo Wild Wings,"1007 w university ave ste 1, georgetown, tx, 7...",7.743232,6.99,8.857553,4.2,208,2,13.79,4.79,NaN,NaN,NaN
3,Buffalo Wild Wings,"1018 crossings blvd, spring hill, tn, 37174, us",7.471596,5.64,8.998419,4.4,104,360+,13.79,4.79,NaN,NaN,NaN
4,Buffalo Wild Wings,"10206 westport rd, louisville, ky, 40241, us",7.906286,7.29,8.727596,4.3,105,900+,13.79,4.79,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,Buffalo Wild Wings,"9402 northlake west dr, charlotte, nc, 28216, us",7.473021,5.29,8.967046,4.0,106,2,13.99,4.79,NaN,NaN,NaN
247,Buffalo Wild Wings,"9435 katy fwy, houston, tx, 77024, us",8.188235,7.14,9.101932,4.1,102,2,14.29,4.79,NaN,NaN,NaN
248,Buffalo Wild Wings,"9600 s i-44 service road, oklahoma city, ok, 7...",8.243495,7.79,8.860370,4.0,206,1,14.49,5.29,NaN,NaN,NaN
249,Buffalo Wild Wings,"9701 roosevelt blvd, philadelphia, pa, 19114, us",7.983267,5.99,9.186781,3.9,212,1,14.79,4.79,NaN,NaN,NaN
250,Buffalo Wild Wings,"985 e fort union blvd, midvale, ut, 84047, us",7.594184,5.29,8.890257,4.0,98,1,13.79,4.79,NaN,NaN,NaN

In [59]:
#Stack all restaurants
correct_order = [
    'restaurant_name', 'restaurant_location', 'menu_item_price mean_non_zero', 
    'menu_item_price median_non_zero', 'menu_item_price std_non_zero', 
 'menu_item count', 'number_of_ratings first', 'specialty_item', 'combo', 'cheeseburger', 'hamburger', 'fries'
]

dfs = [merged_outback, grouped_panera, merged_rr, merged_buff, merged_tgi, merged_apple, merged_denny]
dfs = [df[correct_order] for df in dfs]  # Reorder each DataFrame

ubereats_fullserv_prices = pd.concat(dfs).reset_index(drop=True)

In [62]:
#If there are bad addresses, replace them with the actual address here 

# ubereats_fullserv_prices.loc[434, 'restaurant_location'] = "12811 s tryon st, charlotte, nc, 28273"
ubereats_fullserv_prices.loc[593, 'restaurant_location'] = "20430 us-59, humble, tx, 77338"
ubereats_fullserv_prices.loc[830, 'restaurant_location'] = "13635 san pedro ave, san antonio, tx, 78232"
# ubereats_fullserv_prices.loc[742, 'restaurant_location'] = "2500 sm 291 hwy, independence, mo, 64055"
# ubereats_fullserv_prices.loc[843, 'restaurant_location'] = "9001 shawnee mission pkwy, merriam, ks, 66202"

In [61]:
nan_zip_rows = ubereats_fullserv_prices[ubereats_fullserv_prices['zip'].isna()]
nan_zip_rows

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,menu_item count,number_of_ratings first,specialty_item,combo,cheeseburger,hamburger,fries,state,zip
593,TGI Fridays,"20430 highway 59 n, humble, tx, us, us",23.571618,15.40,26.146536,284,1,NaN,NaN,12.98,NaN,2.86,None,None
830,Denny,"13635 san pedro ave, san antonio, tx, us, us",9.498018,8.41,5.681461,225,800+,NaN,NaN,13.19,NaN,4.77,None,None

In [63]:
pattern = r",\s*([a-zA-Z]{2})\s*,?\s*(\d{5}(?:-\d{4})?)"

def extract_state_zip(address):
    match = re.search(pattern, address)
    if match:
        state, zip_code = match.groups()
        return state, zip_code
    else:
        return None, None

# Apply the function to extract state and zip code
ubereats_fullserv_prices[['state', 'zip']] = ubereats_fullserv_prices['restaurant_location'].apply(lambda x: pd.Series(extract_state_zip(x)))
ubereats_fullserv_prices['zip'] = ubereats_fullserv_prices['zip'].str.split('-').str[0].astype(int)

#Get county 
ubereats_fullserv_prices = ubereats_fullserv_prices.merge(ca_zip_count, on = 'zip')

In [64]:
specific_date = datetime.strptime('09142024', '%m%d%Y')
# Assign the datetime object to the entire 'date' column
ubereats_fullserv_prices['date'] = specific_date
ubereats_fullserv_prices['uber_eats'] = 1
ubereats_fullserv_prices['post_policy'] = 1
ubereats_fullserv_prices['fast_food'] = 0
ubereats_fullserv_prices['local'] = 0

In [65]:
#Save as csv 
ubereats_fullserv_prices.to_csv('processed_prices_ubereats_nonca_fullserv_09142024.csv', index = True)