In [2]:
import json
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [5]:
file_1 = "/Users/alyssanguyen/Desktop/IRLE_scraping/scripts/raw_prices_hardees_nonca_10102024.csv"
# file_2 = "/Users/alyssanguyen/Desktop/IRLE_scraping/csv_files/raw_prices_hardees_non_ca_05162024.csv"

ca_ff = pd.read_csv(file_1)
# hardees = pd.read_csv(file_2)

file_path_2 = "/Users/alyssanguyen/Desktop/IRLE_scraping/csv_files/uszips.csv"
ca_zip_count = pd.read_csv(file_path_2)

#ca_ff['restaurant_name']  = 'Wendy'
ca_ff['restaurant_name']  = 'Hardees'


# ca_ff = pd.concat([carls, hardees])

In [6]:
ca_ff

,menu_item,menu_item_price,menu_item_calories,restaurant_address,restaurant_name
0,5 Piece Nashville Hot Hand-Breaded Chicken Ten...,5.49,670,"100 vandora springs rd., garner, nc, 27529, us",Hardees
1,Mushroom &amp; Swiss,6.09,560,"100 vandora springs rd., garner, nc, 27529, us",Hardees
2,5 Piece Hand-Breaded Chicken Tender Platter,5.49,670,"100 vandora springs rd., garner, nc, 27529, us",Hardees
3,Super Star,6.99,950,"100 vandora springs rd., garner, nc, 27529, us",Hardees
4,Frisco Burger,6.49,860,"100 vandora springs rd., garner, nc, 27529, us",Hardees
...,...,...,...,...,...
462,Double Bacon Cheeseburger,7.99,1010,"875 gold hill rd, fort mill, sc, 29708, us",Hardees
463,Mushroom &amp; Swiss,6.09,560,"875 gold hill rd, fort mill, sc, 29708, us",Hardees
464,Double Mushroom &amp; Swiss,7.59,790,"875 gold hill rd, fort mill, sc, 29708, us",Hardees
465,Big Cheeseburger,4.49,540,"875 gold hill rd, fort mill, sc, 29708, us",Hardees
466,Double Big Cheeseburger,5.99,760,"875 gold hill rd, fort mill, sc, 29708, us",Hardees

In [106]:
ca_zip_count = ca_zip_count[['zip', 'county_name']]

In [107]:
def price_list(x):
    return list(x)
def mean_non_zero(x):
    return np.mean(x[x != 0]) if np.any(x != 0) else 0

def median_non_zero(x):
    return np.median(x[x != 0]) if np.any(x != 0) else 0

def std_non_zero(x):
    return np.std(x[x != 0]) if np.any(x != 0) else 0

In [108]:
#Drop all the columns we don't need 
ca_ff_ = ca_ff.drop(columns=['menu_item_calories'])

#Drop all restaurants with no restaurant address 
#ca_ff_ = ca_ff_.dropna(subset=['restaurant_location'])

#Run if doing restaurant-specific processing i.e. Wendy's Hardee's etc 

ca_ff_ = ca_ff_.rename(columns = {'restaurant_address': "restaurant_location"})
#ca_ff_['restaurant_name'] = 'Carls Jr'
ca_ff_['restaurant_rating'] = np.nan
ca_ff_['number_of_ratings'] = np.nan

In [109]:
ca_ff_ = ca_ff_[ca_ff_['menu_item_price'] != "."]
ca_ff_['menu_item_price'] = ca_ff_['menu_item_price'].str.replace("$", "")
# # Define a function to split prices by "-" or "/"
def split_and_average(price_str):
    # # Split the price string by "-" or "/"
    prices = re.split(r'[-/]', price_str)
    # # Convert prices to float and calculate the average
    #prices = price_str.replace("$", "")
    prices = [float(price) for price in prices]
    return sum(prices) / len(prices)

# Apply the split_and_average function to each row in the menu_item_price column
ca_ff_['menu_item_price'] = ca_ff_['menu_item_price'].apply(split_and_average)

In [110]:
#cleaning up string columns 

ca_ff_['menu_item'] = ca_ff_['menu_item'].str.lower()
ca_ff_['restaurant_location'] = ca_ff_['restaurant_location'].str.lower()
ca_ff_['restaurant_name'] = ca_ff_['restaurant_name'].str.replace('_', ' ')

#remove special characters
ca_ff_['menu_item'] = ca_ff_['menu_item'].apply(lambda x: ''.join(ch for ch in x if ch.isalnum() or ch.isspace()))
ca_ff_['menu_item_price'] = ca_ff_['menu_item_price'].astype(float)

In [111]:
#Filter to just Wendy's
ca_ff_wendy = ca_ff_[ca_ff_['restaurant_name'] == 'Wendy']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_wendy = ca_ff_wendy.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_wendy.columns = [' '.join(col).strip() for col in grouped_wendy.columns.values]

# #Second part of grouping 
wendy_lst = ['daves single', 'french fries', 'jr cheeseburger', 'jr hamburger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_wendy = ca_ff_wendy[ca_ff_wendy['menu_item'].isin(wendy_lst)].sort_values('menu_item')
menu_items_wendy = menu_items_wendy.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_wendy_2 = menu_items_wendy.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_wendy_2[['specialty_item', 'fries', 'cheeseburger', 'hamburger']] = grouped_wendy_2['menu_item_price'].apply(pd.Series)
grouped_wendy_2.drop(columns=['menu_item_price'], inplace=True)

merged_wendy = pd.merge(grouped_wendy, grouped_wendy_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_wendy['combo'] = np.nan
merged_wendy

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,specialty_item,fries,cheeseburger,hamburger,combo
0,Wendy,"1001 main street, brownsville, tx, 78526, us",3.874375,2.990,2.172716,NaN,32,NaN,5.99,2.09,1.99,1.59,NaN
1,Wendy,"101 east ridge road, griffith, in, 46319, us",4.981935,3.890,2.983019,NaN,31,NaN,5.29,2.64,2.69,2.29,NaN
2,Wendy,"101 gateway center lane, baton rouge, la, 7080...",4.543226,3.790,2.221121,NaN,31,NaN,5.69,2.54,2.49,2.19,NaN
3,Wendy,"1013 ridge pike, conshohocken, pa, 19428, us",4.751667,3.640,2.492177,NaN,30,NaN,6.79,2.74,2.39,1.99,NaN
4,Wendy,"10210 berkeley place drive, 120, charlotte, nc...",4.083548,3.290,2.089904,NaN,31,NaN,5.49,2.49,2.19,1.79,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,Wendy,"959 government blvd, mobile, al, 36604, us",4.257742,3.590,2.178545,NaN,31,NaN,5.39,2.29,2.39,2.19,NaN
209,Wendy,"960 east liberty street, york, sc, 29745, us",4.006129,3.290,2.037566,NaN,31,NaN,5.39,2.49,1.99,1.79,NaN
210,Wendy,"963 n beach st, ft.worth, tx, 76111, us",4.572812,3.715,2.629657,NaN,32,NaN,5.99,2.69,2.29,1.79,NaN
211,Wendy,"9703 kennedy avenue, highland, in, 46322, us",4.148333,3.590,2.181211,NaN,30,NaN,5.29,2.54,2.19,1.89,NaN
212,Wendy,"9905 northlake centre pkwy, charlotte, nc, 282...",4.006129,3.290,2.037566,NaN,31,NaN,5.39,2.49,1.99,1.79,NaN

In [79]:
#Filter to just Burger King 
ca_ff_bk = ca_ff_[ca_ff_['restaurant_name'] == 'Burger King']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_bk = ca_ff_bk.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_bk.columns = [' '.join(col).strip() for col in grouped_bk.columns.values]

# #Second part of grouping 
#they don't have a plain hamburger FOR NOW using whopper jr 
bk_lst = ['cheeseburger', 'french fries', 'whopper', 'whopper jr']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_bk = ca_ff_bk[ca_ff_bk['menu_item'].isin(bk_lst)].sort_values('menu_item')
menu_items_bk = menu_items_bk.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_bk_2 = menu_items_bk.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_bk_2[['cheeseburger', 'fries', 'specialty_item', 'hamburger']] = grouped_bk_2['menu_item_price'].apply(pd.Series)
grouped_bk_2.drop(columns=['menu_item_price'], inplace=True)

merged_bk = pd.merge(grouped_bk, grouped_bk_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_bk['combo'] = np.nan
merged_bk

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,specialty_item,hamburger,combo
0,Burger King,100 river oaks cove,4.314000,3.79,2.167815,NaN,25,NaN,2.19,2.89,5.89,2.89,NaN
1,Burger King,1004 north memorial parkway,4.238000,3.49,2.013578,NaN,25,NaN,2.29,2.89,5.89,3.19,NaN
2,Burger King,1027 union ave,4.080476,3.39,1.870550,NaN,21,NaN,2.19,3.19,5.59,3.39,NaN
3,Burger King,10550 south avenue b,4.251538,3.79,2.235049,NaN,26,NaN,2.19,2.79,5.99,2.89,NaN
4,Burger King,1075 south state street,4.522000,3.99,2.232258,NaN,25,NaN,2.29,3.29,5.79,3.29,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,Burger King,819 memorial blvd,4.194762,3.59,1.965046,NaN,21,NaN,2.19,3.39,5.69,3.59,NaN
150,Burger King,8378 w overland rd.,4.555217,3.79,2.323904,NaN,23,NaN,2.29,3.29,5.79,3.29,NaN
151,Burger King,849 university avenue,5.375000,4.09,2.901898,NaN,52,NaN,3.29,4.09,8.19,5.19,NaN
152,Burger King,85 tunnel road,3.956667,3.29,1.879547,NaN,21,NaN,1.99,3.19,5.49,3.09,NaN
153,Burger King,9009 clinton drive,4.016923,3.54,2.129384,NaN,26,NaN,1.89,2.69,5.49,2.59,NaN

In [11]:
#Filter to Carl's Jr 

ca_ff_carls = ca_ff_[ca_ff_['restaurant_name'] == 'Carls Jr']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_carls = ca_ff_carls.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_carls.columns = [' '.join(col).strip() for col in grouped_carls.columns.values]


#Second part of grouping 
carls_lst = ['california classic double cheeseburger', 'single big carl']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_carls = ca_ff_carls[ca_ff_carls['menu_item'].isin(carls_lst)].sort_values('menu_item')
menu_items_carls = menu_items_carls.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_carls_2 = menu_items_carls.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_carls_2[['cheeseburger', 'specialty_item']] = grouped_carls_2['menu_item_price'].apply(pd.Series)
grouped_carls_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_carls = pd.merge(grouped_carls, grouped_carls_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_carls['fries'] = np.nan
merged_carls['combo'] = np.nan
merged_carls['hamburger'] = np.nan

merged_carls

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,specialty_item,fries,combo,hamburger
0,Carls Jr,"1 hallidie plaza, san francisco, ca, 94102, us",10.457083,11.32,2.727613,NaN,24,NaN,5.52,9.26,NaN,NaN,NaN
1,Carls Jr,"1001 veterans blvd, redwood city, ca, 94063, us",9.320417,9.94,2.413786,NaN,24,NaN,4.88,7.55,NaN,NaN,NaN
2,Carls Jr,"101 s union ave, bakersfield, ca, 93307, us",8.506400,8.99,2.147402,NaN,25,NaN,4.99,6.89,NaN,NaN,NaN
3,Carls Jr,"10770 macarthur blvd, oakland, ca, 94605, us",9.320417,9.94,2.413786,NaN,24,NaN,4.88,7.55,NaN,NaN,NaN
4,Carls Jr,"1095 oakland road, san jose, ca, 95112, us",8.402500,8.99,1.752454,NaN,24,NaN,5.99,8.99,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Carls Jr,"854 harbor blvd, west sacramento, ca, 95691, us",8.274400,8.79,1.926531,NaN,25,NaN,4.99,6.89,NaN,NaN,NaN
77,Carls Jr,"871 marina village pkwy, alameda, ca, 94501, us",9.320417,9.94,2.413786,NaN,24,NaN,4.88,7.55,NaN,NaN,NaN
78,Carls Jr,"899 cherry ave, san bruno, ca, 94066, us",9.320417,9.94,2.413786,NaN,24,NaN,4.88,7.55,NaN,NaN,NaN
79,Carls Jr,"939 w. charter way, stockton, ca, 95206, us",8.274400,8.79,1.926531,NaN,25,NaN,4.99,6.89,NaN,NaN,NaN
80,Carls Jr,"996 third ave., chula vista, ca, 91911, us",7.802400,8.09,1.919898,NaN,25,NaN,4.39,6.19,NaN,NaN,NaN

In [32]:
ca_ff_hardee = ca_ff_[ca_ff_['restaurant_name'] == 'Hardees']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_hardee = ca_ff_hardee.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_hardee.columns = [' '.join(col).strip() for col in grouped_hardee.columns.values]


#Second part of grouping 
carls_lst = ['famous star','small cheeseburger', 'small hamburger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_hardee = ca_ff_hardee[ca_ff_hardee['menu_item'].isin(carls_lst)].sort_values('menu_item')
menu_items_hardee = menu_items_hardee.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_hardee_2 = menu_items_hardee.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_hardee_2[['specialty_item', 'cheeseburger', 'hamburger']] = grouped_hardee_2['menu_item_price'].apply(pd.Series)
grouped_hardee_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_hardee = pd.merge(grouped_hardee, grouped_hardee_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_hardee['fries'] = np.nan
merged_hardee['combo'] = np.nan
merged_hardee

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,specialty_item,cheeseburger,hamburger,fries,combo
0,Hardees,"100 vandora springs rd., garner, nc, 27529, us",6.11,6.09,1.763028,NaN,15,NaN,2.79,2.49,NaN,NaN,NaN
1,Hardees,"101 village road ne, leland, nc, 28451, us",6.11,6.09,1.763028,NaN,15,NaN,5.49,2.79,2.49,NaN,NaN
2,Hardees,"12872 70 business highway west, clayton, nc, 2...",6.11,6.09,1.763028,NaN,15,NaN,2.79,2.49,NaN,NaN,NaN
3,Hardees,"140 dale earnhardt boulevard, kannapolis, nc, ...",6.11,6.09,1.763028,NaN,15,NaN,5.49,2.79,2.49,NaN,NaN
4,Hardees,"1420 floral parkway, wilmington, nc, 28403, us",6.11,6.09,1.763028,NaN,15,NaN,5.49,2.79,2.49,NaN,NaN
5,Hardees,"1970 s. 17th street, wilmington, nc, 28401, us",6.11,6.09,1.763028,NaN,15,NaN,5.49,2.79,2.49,NaN,NaN
6,Hardees,"2497 hope mills road, fayetteville, nc, 28304, us",6.11,6.09,1.763028,NaN,15,NaN,2.79,2.49,NaN,NaN,NaN
7,Hardees,"3803 morganton road, fayetteville, nc, 28314, us",6.11,6.09,1.763028,NaN,15,NaN,2.79,2.49,NaN,NaN,NaN
8,Hardees,"3912 north duke street, durham, nc, 27704, us",6.11,6.09,1.763028,NaN,15,NaN,2.79,2.49,NaN,NaN,NaN
9,Hardees,"4260 legion road, hope mills, nc, 28348, us",6.11,6.09,1.763028,NaN,15,NaN,2.79,2.49,NaN,NaN,NaN
10,Hardees,"547 church street north, concord, nc, 28025, us",6.11,6.09,1.763028,NaN,15,NaN,5.49,2.79,2.49,NaN,NaN
11,Hardees,"5601 creedmoor rd, raleigh, nc, 27612, us",6.11,6.09,1.763028,NaN,15,NaN,2.79,2.49,NaN,NaN,NaN
12,Hardees,"5601, castle hayne, nc, 28429, us",6.11,6.09,1.763028,NaN,15,NaN,5.49,2.79,2.49,NaN,NaN
13,Hardees,"5639 hillsborough st., raleigh, nc, 27606, us",6.11,6.09,1.763028,NaN,15,NaN,2.79,2.49,NaN,NaN,NaN
14,Hardees,"6116 farrington road, chapel hill, nc, 27517, us",6.11,6.09,1.763028,NaN,15,NaN,2.79,2.49,NaN,NaN,NaN

In [24]:
ca_ff_hardee

Empty DataFrame
Columns: [menu_item, menu_item_price, restaurant_location, restaurant_name, restaurant_rating, number_of_ratings]
Index: []

In [112]:
stacked = merged_wendy
#pd.concat([merged_carls, merged_hardee])
stacked

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,specialty_item,fries,cheeseburger,hamburger,combo
0,Wendy,"1001 main street, brownsville, tx, 78526, us",3.874375,2.990,2.172716,NaN,32,NaN,5.99,2.09,1.99,1.59,NaN
1,Wendy,"101 east ridge road, griffith, in, 46319, us",4.981935,3.890,2.983019,NaN,31,NaN,5.29,2.64,2.69,2.29,NaN
2,Wendy,"101 gateway center lane, baton rouge, la, 7080...",4.543226,3.790,2.221121,NaN,31,NaN,5.69,2.54,2.49,2.19,NaN
3,Wendy,"1013 ridge pike, conshohocken, pa, 19428, us",4.751667,3.640,2.492177,NaN,30,NaN,6.79,2.74,2.39,1.99,NaN
4,Wendy,"10210 berkeley place drive, 120, charlotte, nc...",4.083548,3.290,2.089904,NaN,31,NaN,5.49,2.49,2.19,1.79,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,Wendy,"959 government blvd, mobile, al, 36604, us",4.257742,3.590,2.178545,NaN,31,NaN,5.39,2.29,2.39,2.19,NaN
209,Wendy,"960 east liberty street, york, sc, 29745, us",4.006129,3.290,2.037566,NaN,31,NaN,5.39,2.49,1.99,1.79,NaN
210,Wendy,"963 n beach st, ft.worth, tx, 76111, us",4.572812,3.715,2.629657,NaN,32,NaN,5.99,2.69,2.29,1.79,NaN
211,Wendy,"9703 kennedy avenue, highland, in, 46322, us",4.148333,3.590,2.181211,NaN,30,NaN,5.29,2.54,2.19,1.89,NaN
212,Wendy,"9905 northlake centre pkwy, charlotte, nc, 282...",4.006129,3.290,2.037566,NaN,31,NaN,5.39,2.49,1.99,1.79,NaN

In [113]:
pattern = r",\s*([a-zA-Z]{2})\s*,?\s*(\d{5}(?:-\d{4})?)"

def extract_state_zip(address):
    match = re.search(pattern, address)
    if match:
        state, zip_code = match.groups()
        return state, zip_code
    else:
        return None, None

# Apply the function to extract state and zip code
stacked[['state', 'zip']] = stacked['restaurant_location'].apply(lambda x: pd.Series(extract_state_zip(x)))
stacked['zip'] = stacked['zip'].str.split('-').str[0].astype(int)

#Get county 
stacked = stacked.merge(ca_zip_count, on = 'zip')

In [82]:
stacked['count'] = np.nan

In [102]:
specific_date = datetime.strptime('09222024', '%m%d%Y')
# Assign the datetime object to the entire 'date' column
stacked['date'] = specific_date
stacked['uber_eats'] = 0
stacked['post_policy'] = 1
stacked['fast_food'] = 1 
stacked['local'] = 0

In [103]:
stacked.to_csv("processed_wendy_nonca_09222014.csv")